apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coach-app

resources:
  - namespace.yaml
  - mongodb/pvc.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml

labels:
  - pairs:
      project: coach-app

