apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coach-app-ingress
  namespace: coach-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: coach.badroot.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coach-app-service
            port:
              number: 80
