apiVersion: v1
kind: Service
metadata:
  name: coach-app-service
  namespace: coach-app
spec:
  selector:
    app: coach-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
