apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: coach-app
data:
  node_env: "development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: coach-app
data:
  api_url: "http://coach-app.local/api"
